language: node_js
node_js:
 - "node"
env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST
- secure: "TsYgfDTXM9DhteoxruftAIm9qbcVFTfBbPmi/Mv9lGkDKZ/b4pputXgbfy2On7dsu5s9Bio/P4Nri61sgVHZm6AJIsNWf2D6Ggiz94oddr0r+7dPp9yqTziPQAKNmMSzCtLff9Dl4BSOiasy/aQy5M+NrD6kXex0xjZyTIEndzk="


services:
  - docker
before_install:
  - docker build -t ayanochkin/learn-travis .
  - docker ps -a
  - docker run ayanochkin/learn-travis /bin/sh -c "cd /root/learn-travis; bundle exec rake test"
  
deploy:
  provider: script
  script: bash docker_push
